name: InfluxDB V2 Source
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: influxv2-data
    required: true
  - name: INFLUXDB_TOKEN
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: false
  - name: INFLUXDB_ORG
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: false
  - name: INFLUXDB_HOST
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: true
  - name: INFLUXDB_MEASUREMENT_NAME
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: false
  - name: task_interval
    inputType: FreeText
    description: ''
    defaultValue: 5m
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
